language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install -r requirements.txt"
  - "pip install coverage"

script: nosetests -v --with-coverage --cover-package=simiki --cover-erase -s

after_success:
  - pip install coveralls
  - coveralls
